# Character Archive Frontend — one-shot setup for Windows (PowerShell + Docker Desktop).
#
# Usage:
#   .\setup.ps1
#   .\setup.ps1 -TorrentDir "C:\Downloads\character-archive-final-torrent"
#   .\setup.ps1 -TorrentDir "C:\Downloads\torrent" -NoWait -SkipTags

param(
    [string]$TorrentDir = "",
    [switch]$NoWait,
    [switch]$SkipTags
)

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

function Write-Info($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
function Write-Err($msg) { Write-Host "Error: $msg" -ForegroundColor Red; exit 1 }

function Test-Docker {
    try {
        docker info | Out-Null
    } catch {
        Write-Err "Docker is not running. Start Docker Desktop and try again."
    }
    try {
        docker compose version | Out-Null
    } catch {
        Write-Err "docker compose (v2) is required."
    }
}

function Resolve-AbsPath([string]$Path) {
    return (Resolve-Path -LiteralPath $Path).Path
}

function Test-TorrentDir([string]$Root) {
    if (-not (Test-Path -LiteralPath $Root -PathType Container)) {
        Write-Err "Torrent directory not found: $Root"
    }
    if (-not (Test-Path -LiteralPath (Join-Path $Root "database.dump") -PathType Leaf)) {
        Write-Err "Missing $Root\database.dump (should be at torrent root)."
    }
    if (-not (Test-Path -LiteralPath (Join-Path $Root "archive\hashed-data") -PathType Container)) {
        Write-Err "Missing $Root\archive\hashed-data — extract archive.7z.* first."
    }
}

function Find-TorrentDir {
    $candidates = @(
        $PWD.Path,
        (Split-Path $PWD.Path -Parent),
        (Join-Path $env:USERPROFILE "Downloads\character-archive-final-torrent"),
        (Join-Path $env:USERPROFILE "Downloads\char-achrive-final\character-archive-final-torrent")
    )
    foreach ($c in $candidates) {
        if ((Test-Path (Join-Path $c "database.dump")) -and (Test-Path (Join-Path $c "archive\hashed-data"))) {
            return $c
        }
    }
    return $null
}

function New-RandomPassword {
    $bytes = New-Object byte[] 16
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    return [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+','').Replace('/','').Substring(0, 20)
}

function Write-EnvFile([string]$Root, [string]$ArchivePath, [string]$DumpPath) {
    $pgPass = New-RandomPassword
    $pgAdminPass = New-RandomPassword
    if (Test-Path ".env") {
        Write-Info "Updating .env (keeping existing passwords if set)"
        $existing = Get-Content ".env" -Raw
        if ($existing -match '(?m)^POSTGRES_PASSWORD=(.+)$') { $pgPass = $Matches[1].Trim() }
        if ($existing -match '(?m)^PGADMIN_DEFAULT_PASSWORD=(.+)$') { $pgAdminPass = $Matches[1].Trim() }
    }
    $lines = Get-Content ".env.example"
    $out = foreach ($line in $lines) {
        if ($line -match '^TORRENT_DIR=') { "TORRENT_DIR=$Root" }
        elseif ($line -match '^ARCHIVE_HOST_PATH=') { "ARCHIVE_HOST_PATH=$ArchivePath" }
        elseif ($line -match '^DATABASE_DUMP_PATH=') { "DATABASE_DUMP_PATH=$DumpPath" }
        elseif ($line -match '^POSTGRES_PASSWORD=') { "POSTGRES_PASSWORD=$pgPass" }
        elseif ($line -match '^PGADMIN_DEFAULT_PASSWORD=') { "PGADMIN_DEFAULT_PASSWORD=$pgAdminPass" }
        else { $line }
    }
    $out | Set-Content -Encoding utf8 ".env"
}

function Write-OverrideFile([string]$ArchivePath, [string]$DumpPath) {
    # Docker Compose on Windows expects forward slashes in bind-mount paths.
    $ArchivePath = $ArchivePath -replace '\\', '/'
    $DumpPath = $DumpPath -replace '\\', '/'
    $yaml = @"
# Auto-generated by setup.ps1 — do not commit.
services:
  frontend:
    volumes:
      - ${ArchivePath}:/archive:ro
  postgres:
    volumes:
      - ${DumpPath}:/docker-entrypoint-initdb.d/database.dump:ro
      - ./init-db.sh:/docker-entrypoint-initdb.d/zz-init-db.sh:ro
"@
    $yaml | Set-Content -Encoding utf8 "docker-compose.override.yml"
}

function Wait-ForDatabase {
    Write-Info "Waiting for database import (this can take 30+ minutes on first run)..."
    $maxAttempts = 360
    for ($i = 1; $i -le $maxAttempts; $i++) {
        try {
            $tables = docker compose exec -T postgres psql -U char_archive -d char_archive -t -c `
                "SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public';" 2>$null
            $tables = ($tables -replace '\s', '')
            if ($tables -and $tables -ne "0") {
                Write-Info "Database ready ($tables public tables)."
                return
            }
        } catch { }
        if ($i % 6 -eq 0) {
            Write-Host "  Still waiting... ($($i * 10)s) — tail logs: docker compose logs -f postgres"
        }
        Start-Sleep -Seconds 10
    }
    Write-Err "Timed out waiting for database. Check: docker compose logs postgres"
}

function Invoke-TagRebuild {
    Write-Info "Rebuilding tag index (needed for tag search)..."
    docker compose exec -T frontend python rebuild_tag_index.py
}

function Show-Success {
    $port = "8080"
    $pgPort = "5050"
    if (Test-Path ".env") {
        foreach ($line in Get-Content ".env") {
            if ($line -match '^FRONTEND_PORT=(.+)$') { $port = $Matches[1].Trim() }
            if ($line -match '^PGADMIN_PORT=(.+)$') { $pgPort = $Matches[1].Trim() }
        }
    }
    Write-Host ""
    Write-Host "Setup complete."
    Write-Host "  Frontend:  http://localhost:$port"
    Write-Host "  pgAdmin:   http://localhost:$pgPort"
    Write-Host ""
    Write-Host "Credentials are in .env (POSTGRES_PASSWORD, PGADMIN_DEFAULT_PASSWORD)."
}

# --- main ---
Test-Docker
New-Item -ItemType Directory -Force -Path "db_data/postgres", "db_data/pgadmin", "import/processed", "import/failed" | Out-Null

if (-not $TorrentDir) {
    $detected = Find-TorrentDir
    if ($detected) {
        Write-Host "Detected torrent folder: $detected"
        $input = Read-Host "Torrent download directory [$detected]"
        $TorrentDir = if ($input) { $input } else { $detected }
    } else {
        $TorrentDir = Read-Host "Torrent download directory (required)"
    }
}

if (-not $TorrentDir) { Write-Err "Torrent directory is required." }

$TorrentDir = Resolve-AbsPath $TorrentDir
Test-TorrentDir $TorrentDir

$ArchivePath = Join-Path $TorrentDir "archive"
$DumpPath = Join-Path $TorrentDir "database.dump"

Write-Info "Torrent dir:  $TorrentDir"
Write-Info "Archive:      $ArchivePath"
Write-Info "Database:     $DumpPath"

Write-EnvFile $TorrentDir $ArchivePath $DumpPath
Write-OverrideFile $ArchivePath $DumpPath

Write-Info "Starting Docker Compose..."
docker compose up -d --build

if ($NoWait) {
    Write-Host "Skipped wait (-NoWait). When import finishes, run:"
    Write-Host "  docker compose exec frontend python rebuild_tag_index.py"
    Show-Success
    exit 0
}

Wait-ForDatabase

if (-not $SkipTags) {
    try { Invoke-TagRebuild } catch {
        Write-Host "Warning: tag index rebuild failed — run later: docker compose exec frontend python rebuild_tag_index.py"
    }
}

Show-Success
