#!/usr/bin/env bash
# Character Archive Frontend — one-shot setup for Linux / macOS / Git Bash.
#
# Usage:
#   ./setup.sh
#   ./setup.sh --torrent-dir /path/to/character-archive-final-torrent
#   ./setup.sh --torrent-dir /path/to/torrent --no-wait --skip-tags

set -euo pipefail
cd "$(dirname "$0")"

TORRENT_DIR=""
NO_WAIT=false
SKIP_TAGS=false

usage() {
  sed -n '2,7p' "$0" | tail -n +2
  exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --torrent-dir)
      TORRENT_DIR="${2:?--torrent-dir requires a path}"
      shift 2
      ;;
    --no-wait)
      NO_WAIT=true
      shift
      ;;
    --skip-tags)
      SKIP_TAGS=true
      shift
      ;;
    -h|--help)
      usage 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage 1
      ;;
  esac
done

die() {
  echo "Error: $*" >&2
  exit 1
}

info() {
  echo "==> $*"
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "$1 is not installed."
}

check_docker() {
  require_cmd docker
  docker info >/dev/null 2>&1 || die "Docker is not running. Start Docker and try again."
  docker compose version >/dev/null 2>&1 || die "docker compose (v2) is required."
}

abs_path() {
  local p="$1"
  if command -v realpath >/dev/null 2>&1; then
    realpath "$p"
  else
    python3 -c 'import os, sys; print(os.path.abspath(os.path.expanduser(sys.argv[1])))' "$p"
  fi
}

validate_torrent_dir() {
  local root="$1"
  [[ -d "$root" ]] || die "Torrent directory not found: $root"
  [[ -f "$root/database.dump" ]] || die "Missing $root/database.dump (should be at torrent root)."
  [[ -d "$root/archive/hashed-data" ]] || die "Missing $root/archive/hashed-data — extract archive.7z.* first."
}

detect_torrent_dir() {
  local candidate dir
  for candidate in \
    "$PWD" \
    "$PWD/.." \
    "$HOME/Downloads/character-archive-final-torrent" \
    "$HOME/Downloads/char-achrive-final/character-archive-final-torrent"; do
    if [[ -f "$candidate/database.dump" && -d "$candidate/archive/hashed-data" ]]; then
      echo "$candidate"
      return 0
    fi
  done
  return 1
}

prompt_torrent_dir() {
  local detected default=""
  if detected="$(detect_torrent_dir 2>/dev/null)"; then
    default="$detected"
    echo "Detected torrent folder: $default"
  fi
  read -r -p "Torrent download directory [${default:-required}]: " TORRENT_DIR
  TORRENT_DIR="${TORRENT_DIR:-$default}"
  [[ -n "$TORRENT_DIR" ]] || die "Torrent directory is required."
}

random_password() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 18 | tr -d '/+=' | head -c 20
  else
    python3 -c 'import secrets; print(secrets.token_urlsafe(16))'
  fi
}

write_env() {
  local root="$1"
  local archive_path="$2"
  local dump_path="$3"
  local pg_pass pgadmin_pass

  if [[ -f .env ]]; then
    info "Updating .env (keeping existing passwords if set)"
    pg_pass="$(grep -E '^POSTGRES_PASSWORD=' .env | cut -d= -f2- || true)"
    pgadmin_pass="$(grep -E '^PGADMIN_DEFAULT_PASSWORD=' .env | cut -d= -f2- || true)"
  fi
  pg_pass="${pg_pass:-$(random_password)}"
  pgadmin_pass="${pgadmin_pass:-$(random_password)}"

  cp .env.example .env
  ROOT="$root" ARCHIVE="$archive_path" DUMP="$dump_path" PG_PASS="$pg_pass" PGADMIN_PASS="$pgadmin_pass" \
  python3 <<'PY'
import os
from pathlib import Path

root = os.environ["ROOT"]
archive = os.environ["ARCHIVE"]
dump = os.environ["DUMP"]
pg_pass = os.environ["PG_PASS"]
pgadmin_pass = os.environ["PGADMIN_PASS"]

lines = Path(".env").read_text().splitlines()
out = []
for line in lines:
    if line.startswith("TORRENT_DIR="):
        out.append(f"TORRENT_DIR={root}")
    elif line.startswith("ARCHIVE_HOST_PATH="):
        out.append(f"ARCHIVE_HOST_PATH={archive}")
    elif line.startswith("DATABASE_DUMP_PATH="):
        out.append(f"DATABASE_DUMP_PATH={dump}")
    elif line.startswith("POSTGRES_PASSWORD="):
        out.append(f"POSTGRES_PASSWORD={pg_pass}")
    elif line.startswith("PGADMIN_DEFAULT_PASSWORD="):
        out.append(f"PGADMIN_DEFAULT_PASSWORD={pgadmin_pass}")
    else:
        out.append(line)
Path(".env").write_text("\n".join(out) + "\n")
PY
}

write_override() {
  local archive_path="$1"
  local dump_path="$2"
  cat > docker-compose.override.yml <<EOF
# Auto-generated by setup.sh — do not commit.
services:
  frontend:
    volumes:
      - ${archive_path}:/archive:ro
  postgres:
    volumes:
      - ${dump_path}:/docker-entrypoint-initdb.d/database.dump:ro
      - ./init-db.sh:/docker-entrypoint-initdb.d/zz-init-db.sh:ro
EOF
}

wait_for_db() {
  # shellcheck source=scripts/db_import_progress.sh
  source "$(dirname "$0")/scripts/db_import_progress.sh"
  wait_for_docker_db_import "$DUMP_PATH"
}

rebuild_tags() {
  info "Rebuilding tag index (needed for tag search)..."
  docker compose exec -T frontend python rebuild_tag_index.py
}

print_success() {
  local port
  port="$(grep -E '^FRONTEND_PORT=' .env | cut -d= -f2- || echo 8080)"
  port="${port:-8080}"
  echo
  echo "Setup complete."
  echo "  Frontend:  http://localhost:${port}"
  echo "  pgAdmin:   http://localhost:$(grep -E '^PGADMIN_PORT=' .env | cut -d= -f2- || echo 5050)"
  echo
  echo "Credentials are in .env (POSTGRES_PASSWORD, PGADMIN_DEFAULT_PASSWORD)."
}

main() {
  check_docker
  mkdir -p db_data/postgres db_data/pgadmin import/processed import/failed

  if [[ -z "$TORRENT_DIR" ]]; then
    prompt_torrent_dir
  fi
  TORRENT_DIR="$(abs_path "$TORRENT_DIR")"
  validate_torrent_dir "$TORRENT_DIR"

  ARCHIVE_PATH="$TORRENT_DIR/archive"
  DUMP_PATH="$TORRENT_DIR/database.dump"

  info "Torrent dir:  $TORRENT_DIR"
  info "Archive:      $ARCHIVE_PATH"
  info "Database:     $DUMP_PATH"

  write_env "$TORRENT_DIR" "$ARCHIVE_PATH" "$DUMP_PATH"
  write_override "$ARCHIVE_PATH" "$DUMP_PATH"

  info "Starting Docker Compose..."
  docker compose up -d --build

  if [[ "$NO_WAIT" == true ]]; then
    echo "Skipped wait (--no-wait). When import finishes, run:"
    echo "  docker compose exec frontend python rebuild_tag_index.py"
    print_success
    exit 0
  fi

  wait_for_db

  if [[ "$SKIP_TAGS" != true ]]; then
    rebuild_tags || echo "Warning: tag index rebuild failed — run later: docker compose exec frontend python rebuild_tag_index.py"
  fi

  print_success
}

main
